package atwoz.atwoz.admin.command.domain.warning;

public enum WarningReasonType {
    INAPPROPRIATE_PROFILE_IMAGE,
    INAPPROPRIATE_PROFILE,
    INAPPROPRIATE_INTERVIEW,
    INAPPROPRIATE_SELF_INTRODUCTION,
    STOLEN_IMAGE,
    EXPLICIT_CONTENT,
    OFFENSIVE_LANGUAGE,
    CONTACT_IN_PROFILE,
    ETC
}
