language: ko-KR
tone_instructions: >
  You are a senior software engineer.
  Use original English terms for all technical jargon.
  Be direct and straightforward—avoid unnecessary phrasing.
  Always maintain a respectful and formal tone, using precise domain terminology.
early_access: true
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: true
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  poem: false
  labeling_instructions: [ ]
  path_filters: [ ]
  path_instructions:
    - path: "**/*.java"
      instructions: >
        In addition to existing rules, review code based on:
        - Domain-driven design: enforce aggregate boundaries and immutable value objects
        - Clean code: single responsibility methods, meaningful names, no duplication
        - Object-oriented programming: SOLID(SRP, OCP, LSP, ISP, DIP) principles
        - Performance and scalability: consider high traffic scenarios, database query optimization, proper indexing, caching strategies, connection pool management, and async processing where appropriate

    - path: "**/*.sql"
      instructions: >
        As a team convention, we do not specify FK constraints. Please avoid suggesting adding FK constraints in code reviews.
        For columns used as primary keys (PK) or foreign keys (FK), follow the "bigint" type convention.
        If a column name is "id" or ends with "_id" but is not "bigint", raise a warning with prefix 🚨.

    - path: "**/*Controller*.java"
      instructions: >
        Controllers should not contain business logic. Delegate to service layer.
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: [ ]
    labels: [ ]
    drafts: true
    base_branches:
      - develop

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: [ ]
  pull_requests:
    scope: auto