version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    env_file:
      - .env
    ports:
      - "${APP_HOST_PORT:-8080}:${APP_CONTAINER_PORT:-8080}"
    volumes:
      - .:/app
      - ./secrets:/etc/credentials:ro
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    ports:
      - "${MYSQL_HOST_PORT:-3308}:${MYSQL_CONTAINER_PORT:-3306}"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "${REDIS_HOST_PORT:-6381}:${REDIS_CONTAINER_PORT:-6379}"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
