spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:atwoz_local}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: true

cloud:
  aws:
    bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ap-northeast-2

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:this-is-secret-key-value-at-least-128-bytes}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800}  # 30분
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600}  # 2주

auth:
  refresh-token-cookie:
    name: refresh_token
    max-age: 2419200 # 4주
    path: /
    same-site: None
    secure: true
    http-only: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_UI_ENABLED:true}

payment:
  app-store:
    key-id: ${APP_STORE_KEY_ID:key-id}
    private-key-string: ${APP_STORE_PRIVATE_KEY_STRING:private-key-string}
    issuer-id: ${APP_STORE_ISSUER_ID:issuer-id}
    environment: ${APP_STORE_ENVIRONMENT:Sandbox}
    bundle-id: ${APP_STORE_BUNDLE_ID:bundle-id}

bizgo:
  api-url: ${BIZGO_API_URL:api-url}
  client-id: ${BIZGO_CLIENT_ID:client-id}
  client-password: ${BIZGO_CLIENT_PASSWORD:client_password}
  from-phone-number: ${BIZGO_FROM_PHONE_NUMBER:from-phone-number}

